"""Contract: what the iOS uploader leaves in Drive is what the unmodified worker imports.

tests/fixtures/ios_contract/ is generated by the CapturaCore Swift tests from the real
UploadQueue, DriveClient and SyncEngine (see its README.md), and a Swift test fails when
the uploader's output stops matching it. Here only worker.Drive.__init__ (rclone token)
and worker.Drive.request (HTTPS) are replaced, by an in-memory Drive that serves that
fixture; worker.run, Drive.get/list/folder/download, verify_folder, verify_audio,
validate_bytes and capture_kind run as shipped. No network; fictional bytes only.
"""
import contextlib
import copy
import hashlib
import io
import json
from pathlib import Path
import re
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / 'tests' / 'fixtures' / 'ios_contract'
sys.path.insert(0, str(ROOT / 'worker'))
import worker  # noqa: E402
from capture_kind import capture_kind  # noqa: E402

ACCOUNT = 'test@example.com'
FOLDER_MIME = 'application/vnd.google-apps.folder'
FIELDS = worker.FIELDS.split(',')
PROPERTY = re.compile(r"properties has \{ key='([^']*)' and value='([^']*)' \}")


class FixtureDrive:
    """The Drive v3 GET surface the worker uses, answered from a fixed state.

    List queries are evaluated clause by clause; a clause it does not model is
    recorded in `unmodeled` instead of being guessed, so a changed worker query
    fails the test rather than silently matching everything.
    """

    def __init__(self, files, media, account=ACCOUNT, ignore_parent_filter=False):
        self.files = {meta['id']: meta for meta in files}
        self.media = media
        self.account = account
        self.ignore_parent_filter = ignore_parent_filter
        self.requests = []
        self.unmodeled = []

    @contextlib.contextmanager
    def serving(self):
        state = self

        def init(drive, config):
            drive.quota_project = None

        def request(drive, path, params):
            return state.request(path, params)

        with patch.object(worker.Drive, '__init__', init), patch.object(worker.Drive, 'request', request):
            yield self

    def request(self, path, params):
        self.requests.append((path, dict(params)))
        if not re.fullmatch(r'(about|files|files/[A-Za-z0-9_-]+)', path):
            raise worker.SafeError('invalid_api_path')
        if path == 'about':
            return self.reply({'user': {'emailAddress': self.account}})
        if path == 'files':
            if params.get('fields') != 'nextPageToken,files(' + worker.FIELDS + ')':
                self.unmodeled.append('fields=' + str(params.get('fields')))
            found = [self.project(meta) for meta in self.files.values() if self.matches(meta, params['q'])]
            return self.reply({'files': sorted(found, key=lambda meta: meta['id'])})
        file_id = path.split('/', 1)[1]
        if file_id not in self.files:
            raise worker.SafeError('drive_http_404')
        if params.get('alt') == 'media':
            return io.BytesIO(self.media[file_id])
        if params.get('fields') != worker.FIELDS:
            self.unmodeled.append('fields=' + str(params.get('fields')))
        return self.reply(self.project(self.files[file_id]))

    def matches(self, meta, query):
        for clause in PROPERTY.sub('PROPERTY', query).split(' and '):
            parent = re.fullmatch(r"'([A-Za-z0-9_-]+)' in parents", clause)
            mime = re.fullmatch(r"mimeType='([^']*)'", clause)
            if clause == 'PROPERTY':
                continue
            elif clause == 'trashed=false':
                ok = meta.get('trashed') is False
            elif clause == "'me' in owners":
                ok = meta.get('ownedByMe') is True
            elif mime:
                ok = meta.get('mimeType') == mime.group(1)
            elif parent:
                ok = self.ignore_parent_filter or parent.group(1) in meta.get('parents', [])
            else:
                self.unmodeled.append(clause)
                return False
            if not ok:
                return False
        properties = meta.get('properties', {})
        return all(properties.get(key) == value for key, value in PROPERTY.findall(query))

    @staticmethod
    def project(meta):
        return {key: copy.deepcopy(value) for key, value in meta.items() if key in FIELDS}

    @staticmethod
    def reply(data):
        return io.BytesIO(json.dumps(data).encode())


class IOSUploaderContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        drive = json.loads((FIXTURE / 'drive.json').read_text(encoding='utf-8'))
        phone = json.loads((FIXTURE / 'phone.json').read_text(encoding='utf-8'))
        cls.folder_id = drive['folder_id']
        cls.files = drive['files']
        cls.folders = [meta for meta in cls.files if meta['mimeType'] == FOLDER_MIME]
        cls.audios = [meta for meta in cls.files if meta['mimeType'] != FOLDER_MIME]
        cls.media = {path.name[:-len('.hex')]: bytes.fromhex(path.read_text(encoding='ascii'))
                     for path in sorted((FIXTURE / 'media').glob('*.hex'))}
        cls.phone = {entry['name']: entry for entry in phone['files']}
        cls.resumed_name = phone['resumed_upload']['name']
        cls.bytes_before_interruption = phone['resumed_upload']['bytes_sent_before_interruption']

    def audio_named(self, name):
        return next(meta for meta in self.audios if meta['name'] == name)

    def run_worker(self, root, drive, probe=False, pinned=True):
        config = dict(root=str(root), expected_account=ACCOUNT)
        if pinned:
            config['folder_id'] = self.folder_id
        with drive.serving():
            result = worker.run(config, probe)
        self.assertEqual(drive.unmodeled, [], 'the worker asked Drive for something this fixture does not model')
        return result

    def imported(self, root):
        return sorted(item.name for item in Path(root).iterdir() if (item / 'original.m4a').is_file())

    def rejection(self, call):
        with self.assertRaises(worker.SafeError) as raised:
            call()
        return str(raised.exception)

    # The fixture itself

    def test_fixture_holds_what_drive_returns_for_the_worker_fields(self):
        self.assertEqual([meta['id'] for meta in self.folders], [self.folder_id])
        self.assertEqual(len(self.audios), 3)
        for meta in self.files:
            self.assertLessEqual(set(meta), set(FIELDS), meta['id'])
            self.assertIs(meta['shared'], False)
            self.assertIs(meta['ownedByMe'], True)
            self.assertIs(meta['trashed'], False)
        self.assertNotIn('size', self.folders[0])
        self.assertNotIn('md5Checksum', self.folders[0])
        for meta in self.audios:
            self.assertEqual(set(meta), set(FIELDS), meta['id'])
            self.assertIsInstance(meta['size'], str, 'Drive encodes int64 as a JSON string')
            self.assertEqual(meta['parents'], [self.folder_id])
            self.assertEqual(len(self.media[meta['id']]), int(meta['size']))
        self.assertEqual(sorted(self.media), sorted(meta['id'] for meta in self.audios))

    def test_phone_never_uploaded_its_partial_file(self):
        partial = [name for name in self.phone if name.endswith('.partial')]
        self.assertEqual(len(partial), 1)
        self.assertIsNone(self.phone[partial[0]]['drive_file_id'])
        self.assertFalse([meta['name'] for meta in self.files if meta['name'].endswith('.partial')])
        uploaded = sorted(name for name, entry in self.phone.items() if entry['drive_file_id'])
        self.assertEqual(sorted(meta['name'] for meta in self.audios), uploaded)

    # Worker code paths, as shipped

    def test_worker_checks_accept_every_upload(self):
        self.assertEqual(worker.verify_folder(self.folders[0], self.folder_id)['id'], self.folder_id)
        with tempfile.TemporaryDirectory() as folder:
            for meta in self.audios:
                path = Path(folder) / meta['id']
                path.write_bytes(self.media[meta['id']])
                self.assertEqual(worker.verify_audio(meta, self.folder_id), int(meta['size']))
                self.assertEqual(worker.validate_bytes(path, meta), self.phone[meta['name']]['sha256'])

    def test_probe_finds_the_phone_folder_without_downloading(self):
        with tempfile.TemporaryDirectory() as root:
            drive = FixtureDrive(self.files, self.media)
            probe = self.run_worker(root, drive, probe=True, pinned=False)
            self.assertEqual(probe['state'], 'private_inbox_verified')
            self.assertEqual(probe['folder_id'], self.folder_id)
            self.assertEqual(probe['errors'], [])
            unpinned = self.run_worker(root, drive, pinned=False)
            self.assertEqual(unpinned['state'], 'waiting_for_exact_folder_configuration')
            self.assertFalse([params for _, params in drive.requests if params.get('alt') == 'media'])
            self.assertEqual(self.imported(root), [])

    def test_run_imports_every_upload_once_with_the_phone_hashes(self):
        with tempfile.TemporaryDirectory() as root:
            drive = FixtureDrive(self.files, self.media)
            first = self.run_worker(root, drive)
            second = self.run_worker(root, drive)
            self.assertEqual((first['state'], first['downloaded'], first['errors']), ('ready', 3, []))
            self.assertEqual((second['state'], second['downloaded'], second['errors']), ('ready', 0, []))
            self.assertEqual(self.imported(root), sorted(meta['id'] for meta in self.audios))
            for meta in self.audios:
                item = Path(root) / meta['id']
                original = (item / 'original.m4a').read_bytes()
                self.assertEqual(original, self.media[meta['id']])
                self.assertEqual(hashlib.sha256(original).hexdigest(), self.phone[meta['name']]['sha256'])
                self.assertEqual(hashlib.md5(original).hexdigest(), self.phone[meta['name']]['md5'])
                self.assertEqual(json.loads((item / 'source.json').read_text())['drive'], meta)

    def test_resumed_upload_is_imported_intact(self):
        meta = self.audio_named(self.resumed_name)
        self.assertLess(self.bytes_before_interruption, int(meta['size']))
        with tempfile.TemporaryDirectory() as root:
            self.run_worker(root, FixtureDrive(self.files, self.media))
            original = (Path(root) / meta['id'] / 'original.m4a').read_bytes()
        self.assertEqual(hashlib.sha256(original).hexdigest(), self.phone[self.resumed_name]['sha256'])

    def test_capture_kind_survives_the_round_trip(self):
        kinds = {}
        with tempfile.TemporaryDirectory() as root:
            self.run_worker(root, FixtureDrive(self.files, self.media))
            for meta in self.audios:
                source = json.loads((Path(root) / meta['id'] / 'source.json').read_text())
                kinds[meta['name']] = capture_kind(source['drive'])
        self.assertEqual(kinds, {name: entry['capture_kind'] for name, entry in self.phone.items() if entry['drive_file_id']})
        self.assertEqual(sorted(kinds.values()), ['ambient_audio', 'ambient_audio', 'dictated_note'])

    # Negative controls: the same state with one thing wrong

    def run_tampered(self, name, change, media_change=None, **drive_options):
        files = copy.deepcopy(self.files)
        target = next(meta for meta in files if meta['name'] == name)
        target_id = target['id']
        change(target)
        media = dict(self.media)
        if media_change:
            media[target_id] = media_change(media[target_id])
        with tempfile.TemporaryDirectory() as root:
            result = self.run_worker(root, FixtureDrive(files, media, **drive_options))
            imported = self.imported(root)
        return result, imported, target, media

    def assert_run_rejects(self, code, name, change, media_change=None, **drive_options):
        result, imported, target, _ = self.run_tampered(name, change, media_change, **drive_options)
        self.assertEqual(result['errors'], [code])
        self.assertEqual(result['state'], 'needs_review')
        self.assertEqual(result['downloaded'], 2, 'the other uploads are still imported')
        self.assertNotIn(target['id'], imported)
        return target

    def test_tampered_md5_is_rejected_after_download(self):
        def tamper(meta):
            meta['md5Checksum'] = '0' * 32
        target = self.assert_run_rejects('download_checksum_mismatch', self.resumed_name, tamper)
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / 'audio'
            path.write_bytes(self.media[target['id']])
            self.assertEqual(self.rejection(lambda: worker.validate_bytes(path, target)), 'download_checksum_mismatch')

    def test_corrupted_bytes_are_rejected_after_download(self):
        def flip_last_byte(data):
            return data[:-1] + bytes([data[-1] ^ 0xFF])
        self.assert_run_rejects('download_checksum_mismatch', self.resumed_name, lambda meta: None, flip_last_byte)

    def test_shared_file_is_rejected(self):
        def share(meta):
            meta['shared'] = True
        target = self.assert_run_rejects('invalid_audio_metadata', self.resumed_name, share)
        self.assertEqual(self.rejection(lambda: worker.verify_audio(target, self.folder_id)), 'invalid_audio_metadata')

    def test_oversize_file_is_rejected(self):
        def oversize(meta):
            meta['size'] = str(worker.MAX_AUDIO + 1)
        target = self.assert_run_rejects('audio_size_out_of_bounds', self.resumed_name, oversize)
        self.assertEqual(self.rejection(lambda: worker.verify_audio(target, self.folder_id)), 'audio_size_out_of_bounds')

    def test_wrong_mime_type_is_rejected(self):
        def relabel(meta):
            meta['mimeType'] = 'application/octet-stream'
        target = self.assert_run_rejects('invalid_audio_metadata', self.resumed_name, relabel)
        self.assertEqual(self.rejection(lambda: worker.verify_audio(target, self.folder_id)), 'invalid_audio_metadata')

    def test_file_in_another_folder_is_never_imported(self):
        def move(meta):
            meta['parents'] = ['someOtherFolder']
        # Drive itself filters by parent, so the file is not even listed...
        result, imported, target, _ = self.run_tampered(self.resumed_name, move)
        self.assertEqual((result['state'], result['downloaded'], result['errors']), ('ready', 2, []))
        self.assertNotIn(target['id'], imported)
        # ...and if a listing ever returned it, the worker's own parent check refuses it.
        self.assert_run_rejects('invalid_audio_metadata', self.resumed_name, move, ignore_parent_filter=True)
        self.assertEqual(self.rejection(lambda: worker.verify_audio(target, self.folder_id)), 'invalid_audio_metadata')

    def test_partial_name_gets_no_note_provenance(self):
        # The worker has no file-name rule: keeping `.partial` files off Drive is the
        # phone's job (test_phone_never_uploaded_its_partial_file and the Swift contract
        # test). If one ever arrived, it would be imported only as ambient audio.
        def rename(meta):
            meta['name'] += '.partial'
        result, imported, target, _ = self.run_tampered(self.dictated_note_name(), rename)
        self.assertEqual((result['state'], result['downloaded'], result['errors']), ('ready', 3, []))
        self.assertIn(target['id'], imported)
        self.assertEqual(target['properties']['captureKind'], 'dictated_note')
        self.assertEqual(capture_kind(target), 'ambient_audio')

    def test_shared_folder_stops_the_probe(self):
        files = copy.deepcopy(self.files)
        next(meta for meta in files if meta['id'] == self.folder_id)['shared'] = True
        with tempfile.TemporaryDirectory() as root:
            probe = self.run_worker(root, FixtureDrive(files, self.media), probe=True, pinned=False)
            run = self.run_worker(root, FixtureDrive(files, self.media))
            self.assertEqual(self.imported(root), [])
        self.assertEqual((probe['state'], probe['errors']), ('error', ['folder_not_private_capture']))
        self.assertEqual((run['state'], run['errors']), ('error', ['folder_not_private_capture']))

    def dictated_note_name(self):
        return next(name for name, entry in self.phone.items() if entry['capture_kind'] == 'dictated_note')


if __name__ == '__main__':
    unittest.main()
